###########
# site.url, site.title

title: 'Jekyll Theme of the Month Series | Planet Jekyll'
url:   'http://planetjekyll.github.io/themes'

########
# more settings

permalink: /:title.html

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded


###
# todo/check:
#   possible to exclude *.ini ???

exclude:
- README.md


safe: true
lsi: false

